server:
  port: 8888

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server-local
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
        #  management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#    endpoint:
#      health:
#        show-details: ALWAYS
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
#    compatibility-verifier:
#      enabled: false


#logging:
#  file:
#    path: logs/
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_}"


management:
  tracing:
    sampling:
      probability: 1